### ISSUE TITLE
Invalidate queries not working as expected

### ISSUE THREAD

**Issue by talksik** [OrJDev/solid-trpc#10]
I have been trying to see what is wrong with the internal `getArrayQueryKey` and I think it might be a bug potentially.

Trying to invalidate a query does not work as expected. Has this been tested?

I set the queryKey of a query to "getUsers" and using 
```
const utils = trpc.useContext()

utils.invalidate(["getUsers"]) 
```

Thank you so much for your help!

**Comment by OrJDev** [comment]
Yes this has been tested and used, Could you send me the entire page? It should be something like

utils.getUsers.invalidate()

Or

utils.users.getUsers.invalidate()

**Comment by talksik** [comment]
Thank the lord, you are so helpful and responsive.

This works now! I didn't know that there were handler decorater for the utils object.

```
  const query = trpc.getUsers.useQuery();

  const utils = trpc.useContext();
  const invalidate = () => {
    utils.getUsers.invalidate();
  };
```

**Comment by OrJDev** [comment]
Yes in v10 almost everything is a proxy. Glad i could help. If you face any other issue feel free to make an issue.

**Comment by talksik** [comment]
Thank you so much for your work on this!

Do you mind if I add to the documentation? 

Also, I'm no typescript or solidjs expert but should we remove the utils.validate method and only keep the procedure related util methods? I tried different ways of using the utils.validate and I don't think it works

**Comment by OrJDev** [comment]
> Thank you so much for your work on this!
> 
> 
> 
> Do you mind if I add to the documentation? 
> 
> 
> 
> Also, I'm no typescript or solidjs expert but should we remove the utils.validate method and only keep the procedure related util methods?

This is an exact copy of the react one, as long as they keep it I don't want to delete it. 

Also prs are appreciated so if you want to add it to the docs feel free to do so, 
even tho it's already mentioned in the official trpc docs trpc.io

**Comment by OrJDev** [comment]
Appreciate your sponsor very much, thank you 😎
