### ISSUE TITLE
How to access cookies in SSR

### ISSUE THREAD

**Issue by Tanner-Scadden** [OrJDev/solid-trpc#12]
Hello! Would love an example of how to access the cookies in SSR.  Currently trying to pass this into `httpBatchLink` but the context is always an empty object from `solid-start`. Thanks! 

```ts
async headers() {
        if (AppConfig.isServer) {
          const context = useRequest();
          const token = await getToken(context.request);
          return {
            Authorization: `Bearer ${token ?? ""}`,
          };
        } else {
          const token = ClientCookieManager.getToken();
          return {
            Authorization: `Bearer ${token ?? ""}`,
          };
        }
      },
```

**Comment by OrJDev** [comment]
We discussed this on discord but for reader's knowledge: 

Use `solid-trpc@start-ssr` (the ssr branch on github), you can access the page event by providing the `config` callback to `createTRPCSolidStart`
