### ISSUE TITLE
eslint warning

### ISSUE THREAD

**Issue by adammetal** [OrJDev/solid-trpc#13]
This line causes eslint warning:

```TypeScript
const [count, setCount] = createSignal("");
trpc.xyz.useQuery(() => Number(count()))
```

```
warning  This function should be passed to a tracked scope (like createEffect) or an event handler because it contains reactivity. Details: https://github.com/solidjs-community/eslint-plugin-solid/blob/main/docs/reactivity.md  solid/reactivity
```

And it points to the arrow function i used in useQuery. The funny thing is this works perfectly and do  exactly what i want, its update when the count signal changes so i usually just ignore this warnings but somehow its bothers me. Can you give some examples how to do this right or the eslint plugin needs some update?

Thanks :)

Btw Great lib! I love it.

**Comment by OrJDev** [comment]
hey there

yes this is a valid code it is a known bug within solid eslint - (check this issue - https://github.com/solidjs-community/eslint-plugin-solid/issues/54)

it was recently fixed tho, could you trying upgrading to the latest version?

**Comment by adammetal** [comment]
Hey,

Thanks :) Its working like a charm now. No more warnings.
Thanks for the quick answer! :)
