### ISSUE TITLE
Passing opts to useQuery is not working

### ISSUE THREAD

**Issue by Jayphen** [OrJDev/solid-trpc#15]
Hey, in a project created with create jd app (solid-trpc@0.1.0-sssr.6) —

Passing anything as the second argument causes a crash.

![image](https://user-images.githubusercontent.com/329184/216844713-cc25afce-9012-4bbc-bd31-2509c3a51a20.png)

![image](https://user-images.githubusercontent.com/329184/216844693-d6f7629f-33d4-42ac-9010-e4315f5fa7d0.png)

**Comment by OrJDev** [comment]
That is because the ssr version is expecting a function that returns an object (solid accessor) so instead of { enabled: false } it should be ()=> ({ enabled: false })

**Comment by Jayphen** [comment]
Ah thank you, that works.
