### ISSUE TITLE
`useQuery` options missing `onSuccess`

### ISSUE THREAD

**Issue by sebastiansandqvist** [OrJDev/solid-trpc#19]
Following the example from the Readme, it appears that there is no support for the `onSuccess` method on the `useQuery` options.

<img width="601" alt="Screenshot 2023-08-16 at 04 12 20" src="https://github.com/OrJDev/solid-trpc/assets/2024396/3eb606fa-1e02-4787-ad42-072b4bd308c0">

Other properties, such as `refetchOnMount`, work just fine:
<img width="580" alt="Screenshot 2023-08-16 at 04 10 37" src="https://github.com/OrJDev/solid-trpc/assets/2024396/b41a87e7-cfdf-4f58-92f6-b4a0c9801b31">

Is there an error in my usage here? Or perhaps an issue with solid-query?

<img width="1029" alt="Screenshot 2023-08-16 at 04 18 07" src="https://github.com/OrJDev/solid-trpc/assets/2024396/9ca28421-c3c6-4728-929e-01dea2a04b84">

**Comment by leanderriefel** [comment]
can confirm and would be nice to fix

**Comment by OrJDev** [comment]
Its not a bug, since solid query v5 onSuccess is no longer an option, check out their docs for more info
