### ISSUE TITLE
`invalidate` and `refetch` don't seem to work when called from `useContext()`

### ISSUE THREAD

**Issue by pablo-abc** [OrJDev/solid-trpc#2]
Hello!

I've been experimenting with this using `create-jd-app`, (wonderful work!) and it seems I've hit a bit of an issue.

I'm using v10 (0.0.7-beta.1).

I have the following code in a component:

```typescript
  const query = trpc.account.findAll.useQuery();
  const context = trpc.useContext();
  const mutation = trpc.account.create.useMutation({
    onSuccess() {
      context.account.findAll.invalidate();
    },
  });
```

When running the mutation, the call to `invalidate` (or `refetch`) don't trigger a refetch of the `account.findAll` query as I'd hope.

My server code:

```typescript
import { z } from 'zod';
import { procedure, router } from '../utils';

export default router({
  create: procedure
    .input(
      z.object({
        username: z.string().min(1),
      })
    )
    .mutation(({ input, ctx }) => {
      return ctx.prisma.account.create({ data: input });
    }),
  findAll: procedure.query(({ ctx }) => ctx.prisma.account.findMany()),
});
```

**Comment by OrJDev** [comment]
hey there, yes you are right it seems to be broken in .7 beta,
 i was just working on `rc` and it seems to be fixed in there so please update your trpc client and server version
```bash
npm install solid-trpc@next solid-start-trpc@latest @trpc/server@10.0.0-rc.2 @trpc/client@10.0.0-rc.2
```
or run `npm create jd-app@latest` to create a new project with all of the above,
 let me know if its working as expected.

**Comment by pablo-abc** [comment]
Works as expected, thanks!
