### ISSUE TITLE
Warning in console with basic useQuery

### ISSUE THREAD

**Issue by utrolig** [OrJDev/solid-trpc#3]
![image](https://user-images.githubusercontent.com/16609718/202841016-9ab1e1a0-b95c-4456-afe6-da7877cc79a8.png)

How to reproduce

1. Clone SolidJS template app
2. Follow solid-trpc installation steps
3. use a trpc query inside a component

**Comment by OrJDev** [comment]
ye this seem to happen because i'm trying add the `trpc` obj to the solid proxy

```ts
    hook.trpc = useHookResult({
      path: pathAndInput()[0],
    });
```

resolved, please run

```bash
npm install solid-trpc@0.0.10-rc.1
```

and let me know

**Comment by utrolig** [comment]
That indeed seems to fix it.
Can't see the warning anymore!

Thanks for the quick fix and awesome work with the project!

**Comment by OrJDev** [comment]
(:

Also if you use solid start i would recommend using [create jd app](https://github.com/orjdev/create-jd-app) instead of doing it by hand, if you use solid js its fine.
