### ISSUE TITLE
Type instantiation excessively deep

### ISSUE THREAD

**Issue by talksik** [OrJDev/solid-trpc#6]
My intellisense in vs code is not working and keeps loading.

My configuration is simply the get started with a monorepo where my client imports the approuter type. There is something that might be looping when put together solidquery. However, for some reason, even just the server file which is the standard trpc hello world struggles with inferring types.

Would appreciate any help thank you!

server app router file below
```
import { inferAsyncReturnType, initTRPC } from '@trpc/server';
import * as trpcExpress from '@trpc/server/adapters/express';
import { z } from 'zod';

export const createContext = ({
  req,
  res,
}: trpcExpress.CreateExpressContextOptions) => {
  const getUser = () => {
    if (req.headers.authorization !== 'secret') {
      return null;
    }
    return {
      name: 'alex',
    };
  };

  return {
    req,
    res,
    user: getUser(),
  };
};
type Context = inferAsyncReturnType<typeof createContext>;

const t = initTRPC.context<Context>().create();

export const appRouter = t.router({
  hello: t.procedure
    .input(z.object({ test: z.string() }))
    .query(({ input, ctx }) => {
      return `hello ${input ?? ctx.user?.name ?? 'world'}`;
    }),
});

export type AppRouter = typeof appRouter;

```

client side file 
``` 
import type { AppRouter } from '@flowy/server/src/router';
import { createTRPCSolid } from 'solid-trpc';
import { httpBatchLink } from '@trpc/client';
import { QueryClient } from '@tanstack/solid-query';

export const trpc = createTRPCSolid<AppRouter>();
export const client = trpc.createClient({
  links: [
    httpBatchLink({
      url: 'http://localhost:8080/trpc',
    }),
  ],
});
export const queryClient = new QueryClient();

```

**Comment by OrJDev** [comment]
I have no idea what is the error in your code editor exactly, what is your typescript version? Would it work in other code editors like webstrom?

**Comment by OrJDev** [comment]
When restarting vscode / typescript server would it work?

Control + shift + p

Restart ts server

**Comment by talksik** [comment]
thanks for the suggestion, unfortunately restarting ts server doesnt work. I will try the other suggestion of using another editor.

I am on 4.4.4 typescript version.

There is no error. Intellisense just struggles forever. Hovering on the types and objects shows any because it cant infer or gives up. Thus when I useQuery, what happens is that it autocomplete doesn't work, but I can manually type in the endpoint and object and it works compile time as expected

**Comment by talksik** [comment]
I will try to see if some other editor can do it

**Comment by talksik** [comment]
@OrJDev  you are awesome! it worked in webstorm!

do you have any ideas on how to increase inference in vscode? it seems odd that it doesn't work as expected right out of the box? perhaps increasing memory allocation or something?

**Comment by OrJDev** [comment]
I would recommend removing everything vscode related and reinstall it

**Comment by OrJDev** [comment]
Its either a ts server error or something is wrong in your vscode configuration

**Comment by OrJDev** [comment]
Anyways I'm closing this just to not mislead other people but ofc feel free to update me in here even tho its closed
