### ISSUE TITLE
setData re renders the whole app

### ISSUE THREAD

**Issue by adammetal** [OrJDev/solid-trpc#9]
Hi, great lib! I tried to use this library for a hobby love project and its great. Working fine, i just have one concern. When i update the state with useContext in a mutation onSuccess, i noticed the whole dom is re rendering. Every element on the page. The body will emptied and after rebuild the whole again. It is normal? I think something happens with the contexts or i don't know. I use the solid start with trpc, prisma and tailwindcss.

**Comment by adammetal** [comment]
Another thing. I had to double check but the same issue applies to refetches. If i refetch in one component the whole app will be re rendered.

**Comment by OrJDev** [comment]
Could you share the exact code? Because it shouldn't happen and it seems to work for me (data invalidating onSuccess).

**Comment by OrJDev** [comment]
Could you share the exact code? I believe that nothing could go wrong and it shouldn't be happening (unless its something in solidquery) but just to make sure

**Comment by adammetal** [comment]
Sure.

This is the index.tsx file in the routes folder. It uses one endpoint for get the uploaded images.
```TypeScript
import { type VoidComponent, Switch, Match, For } from "solid-js";
import { Title } from "solid-start";
import Image from "~/components/Image";
import Upload from "~/components/Upload";
import { trpc } from "~/utils/trpc";

const Home: VoidComponent = () => {
  const images = trpc.getImages.useQuery(undefined, {
    get staleTime() {
      return Infinity;
    },
    get cacheTime() {
      return Infinity;
    }
  });

  return (
    <>
      <Title>Home</Title>
      <div>
        <Upload />
        <Switch
          fallback={
            <div class="grid grid-cols-2">
              <For each={images.data}>{(image) => <Image image={image} />}</For>
            </div>
          }
        >
          <Match when={images.isLoading}>
            <div class="font-bold text-2xl text-gray-500">Loading...</div>
          </Match>
        </Switch>
      </div>
    </>
  );
};

export default Home;
```

And this is the Image component:
```TypeScript
/* eslint-disable solid/event-handlers */
import { type Component, Show, createSignal } from "solid-js";
import { trpc } from "~/utils/trpc";
import type { RouterOutput } from "~/server/trpc/router/_app";
import Lines from "./Lines";

const Image: Component<{
  image: RouterOutput["getImageById"];
}> = (props) => {
  const utils = trpc.useContext();
  const [scry, setScry] = createSignal(false);
  
  const ocrMutation = trpc.requestImageOcr.useMutation({
    onSettled() {
      utils.getImageLines.refetch({ id: props.image.id });
    }
  });
  
  const scryMutation = trpc.startImageScry.useMutation();

  const open = () => {
    window.open(props.image.url, "blank");
  };

  const startOcr = () => {
    ocrMutation.mutate({ id: props.image.id });
  };

  const startScry = () => {
    scryMutation.mutate({ id: props.image.id });
    setScry(true);
  };

  const stopScry = () => {
    setScry(false);
  }

  return (
    <div class="m-4 bg-slate-200 relative p-4">
      <img src={props.image.url} onDblClick={open} class="w-96 mx-auto" />
      <div class="text-center p-1">
        <Show
          when={ocrMutation.isLoading}
          fallback={
            <button onClick={startOcr} class="bg-slate-300 m-1 p-4">
              Start OCR
            </button>
          }
        >
          Ocr in progress
        </Show>
        <Show
          when={scryMutation.isLoading}
          fallback={
            <>
              <button onClick={startScry} class="bg-slate-300 m-1 p-4">
                Start Scry
              </button>
              <button onClick={stopScry} class="bg-slate-300 m-1 p-4">
                Stop Scry
              </button>
            </>
          }
        >
          Scry starting
        </Show>
      </div>
      <Lines scry={scry()} image={props.image.id} />
    </div>
  );
};

export default Image;
```
The ocr mutation onSettled callback makes the whole app re renders. The endpoint sends this image to a free ocr api and get some lines from that image. And we can edit, add or delete those lines with the Lines component. But when i have more than 1 image, and i call the ocr mutation, not just the "target" component renders the Lines component, but the whole page re renders. What i missed?

**Comment by OrJDev** [comment]
What do you mean rerender? You mean the screen flashes? (Becomes plain for a moment) Solid doesn't even know how to rerender your component.

If so, would wrapping your main Switch with a Suspense solve it?


```tsx
<Suspense>
<Switch>
<> </>
</Switch>
</Suspense>
```

**Comment by adammetal** [comment]
Oh, it worked! Whoa! If i put suspense as a parent of the Lines component and i optimisticly mutate of refetch those specific component datas, the blinking is dissapear and now just that components rerender what needed. Can you explain me why the Suspense solves this magically? :D

**Comment by OrJDev** [comment]
> Oh, it worked! Whoa! If i put suspense as a parent of the Lines component and i optimisticly mutate of refetch those specific component datas, the blinking is dissapear and now just that components rerender what needed. Can you explain me why the Suspense solves this magically? :D

It is yet not confirmed but we (me and a guy who works on Solid) believe that it is trying to trigger the main Suspense (check your root.tsx it should be wrapping your Body), anyways make sure to always wrap trpc switches with Suspense -
 I really see no reason why not.
